export const items = [{'item_id': 11, 'list_id':2, 'item':'Pumpkin Seeds', 'type':'seed'},
                      {'item_id': 12, 'list_id':2, 'item':'Potato Seeds', 'type':'seed'},
                      {'item_id': 13, 'list_id':2, 'item':'Spade', 'type':'tool'},
                      {'item_id': 14, 'list_id':2, 'item':'Trowel', 'type':'tool'},
                      {'item_id': 15, 'list_id':2, 'item':'Pot', 'type':'utility'},
                      {'item_id': 16, 'list_id':3, 'item':'Pumpkin Seeds', 'type':'seed'},
                      {'item_id': 17, 'list_id':3, 'item':'Potato Seeds', 'type':'seed'},
                      {'item_id': 18, 'list_id':3, 'item':'Spade', 'type':'tool'},
                      {'item_id': 19, 'list_id':3, 'item':'Trowel', 'type':'tool'},
                      {'item_id': 20, 'list_id':3, 'item':'Pot', 'type':'utility'},
                      {'item_id': 21, 'list_id':4, 'item':'Pumpkin Seeds', 'type':'seed'},
                      {'item_id': 22, 'list_id':4, 'item':'Potato Seeds', 'type':'seed'},
                      {'item_id': 23, 'list_id':4, 'item':'Spade', 'type':'tool'},
                      {'item_id': 24, 'list_id':4, 'item':'Trowel', 'type':'tool'},
                      {'item_id': 25, 'list_id':4, 'item':'Pot', 'type':'utility'}];
